name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 17 (required for modern Android projects)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Make the Gradle wrapper executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Build the project and download dependencies
      - name: Build with Gradle
        run: ./gradlew build

      # Check Kotlin code formatting with lint
      - name: Run lint
        run: ./gradlew lint

      # Run unit tests
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      # Run screen tests
      - name: Set up Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel
          script: ./gradlew connectedDebugAndroidTest

