name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Make the Gradle wrapper executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Check if project compile both in debug and release
      - name: Assemble Debug and Release
        run: ./gradlew assembleDebug assembleRelease

      # Build the project and download dependencies
      - name: Build with Gradle
        run: ./gradlew build

      # Check Kotlin code formatting with lint
      - name: Run lint
        run: ./gradlew lint

      # Upload Lint Report
      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: app/build/reports/lint-results.html

      # Run unit tests
      - name: Run unit tests
        run: ./gradlew testReleaseUnitTest
